---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: stonesoup-integeration-tests
spec:
  timeouts:
    finally: "0h20m0s"
  params:
    - name: repo_url
    - name: revision
    - name: repo_owner
    - name: target_branch
  workspaces:
    - name: source
    - name: kubeconfig-dir
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
    - name: produce-cluster-name
      runAfter:
        - "fetch-repository"
      taskRef:
        name: generate-cluster-name
    - name: deploy-cluster
      runAfter:
        - "produce-cluster-name"
      params:
        - name: image
          value: "quay.io/openshift-release-dev/ocp-release:4.12.2-x86_64"
        - name: region
          value: "us-east-1"
        - name: cluster-name
          value: "$(tasks.produce-cluster-name.results.cluster-name)"
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
        - name: output
          workspace: shared-workspace
        - name: source
          workspace: source
      taskRef:
        name: deploy-cluster
    - name: stonesoupe-e2e-test
      runAfter:
        - "deploy-cluster"
      workspaces:
        - name: kubeconfig-dir
          workspace: shared-workspace
        - name: source
          workspace: source
      params:
        - name: repo_url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
        - name: repo_owner
          value: $(params.repo_owner)
        - name: target_branch
          value: $(params.target_branch)
      taskRef:
        name: stonesoup-tests
  finally:
    - name: destroy-cluster
      when:
        - input: "$(tasks.deploy-cluster.status)"
          operator: notin
          values: ["None"]
      params:
        - name: cluster-name
          value: "$(tasks.produce-cluster-name.results.cluster-name)"
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
        - name: source
          workspace: source
      taskRef:
        name: destroy-cluster
