---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: copy-plnsvc-code
spec:
  params:
    - name: target_branch
  workspaces:
    - name: kubeconfig-dir
      description: The kubeconfig of new cluster will be stored onto the volume backing this Workspace
    - name: source
  steps:
    - name: copy-code-to-container
      image: quay.io/redhat-pipeline-service/ci-runner:$(params.target_branch)
      resources:
        requests:
          memory: 500Mi
          cpu: 300m
      workingDir: "$(workspaces.source.path)"
      env:
        - name: KUBECONFIG
          value: "$(workspaces.kubeconfig-dir.path)/kubeconfig"
      command:
        - $(workspaces.source.path)/ci/images/ci-runner/hack/bin/copy-plnsvc-code.sh
