---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: destroy-existing-cluster
spec:
  params:
    - name: target_branch
    - name: region
      description: ocp cluster region where you want to provision
  workspaces:
    - name: source
  steps:
    - name: destroy
      image: quay.io/redhat-pipeline-service/ci-runner:$(params.target_branch)
      env:
        - name: BW_CLIENTID
          valueFrom:
            secretKeyRef:
              name: hypershift-bitwarden
              key: "BW_CLIENTID"
        - name: BW_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: hypershift-bitwarden
              key: "BW_CLIENTSECRET"
        - name: BW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hypershift-bitwarden
              key: "BW_PASSWORD"
        - name: REGION
          value: "$(params.region)"
      command:
        - $(workspaces.source.path)/ci/images/ci-runner/hack/bin/cleanup-expired-clusters.sh
