---
name: Build and push images to quay
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions: read-all
jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v3

      - name: Get the short sha
        id: vars
        run: echo "sha_short=$(echo ${{ github.sha }} | cut -b -7)" > $GITHUB_OUTPUT

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            access-setup:
              - '.github/workflows/build-push-images.yaml'
              - 'operator/images/access-setup/**'
              - 'shared/**'
            ci-runner:
              - '.github/workflows/build-push-images.yaml'
              - 'ci/images/ci-runner/**'
              - 'shared/**'
            cluster-setup:
              - '.github/workflows/build-push-images.yaml'
              - 'operator/images/cluster-setup/**'
              - 'shared/**'
            dependencies-update:
              - '.github/workflows/build-push-images.yaml'
              - 'developer/images/dependencies/**'
              - 'shared/**'
            devenv:
              - '.github/workflows/build-push-images.yaml'
              - 'developer/images/devenv/**'
              - 'shared/**'
            e2e-test-runner:
              - '.github/workflows/build-push-images.yaml'
              - 'ci/images/e2e-test-runner/**'
              - 'shared/**'
            quay-upload:
              - '.github/workflows/build-push-images.yaml'
              - 'ci/images/quay-upload/**'
            static-checks:
              - '.github/workflows/build-push-images.yaml'
              - 'ci/images/static-checks/**'
              - 'shared/**'
            update-pipeline-service:
              - '.github/workflows/build-push-images.yaml'
              - 'operator/images/update-pipeline-service/**'
              - 'shared/**'
            vulnerability:
              - '.github/workflows/build-push-images.yaml'
              - 'ci/images/vulnerability-scan/**'

      # Build and push devenv image, tagged with the branch name and the commit SHA.
      - name: Build devenv Image
        id: build-image-devenv
        if: steps.filter.outputs.devenv == 'true'
        uses: redhat-actions/buildah-build@v2
        with:
          image: devenv
          context: .
          tags: latest ${{ steps.vars.outputs.sha_short }} ${{ github.ref_name }}
          containerfiles: |
            ./developer/images/devenv/Dockerfile
